### ISSUE TITLE
Simple tasks run lots of times

### ISSUE THREAD

**Issue by sagivf** [iamkevla/agenda-rdb#1]
I would really like to use this, so thanks for sharing.

Problem is a simple `agenda.schedule('in 10 seconds', 'task');` for example runs multiple times.
same for `agenda.now`.

Any ideas what I can look for?

**Comment by sagivf** [comment]
I think I found the problem.

https://github.com/iamkevla/agenda-rdb/pull/2

**Comment by avivroth** [comment]
Was this fixed yet?  I'm having the same problem.  Is there a workaround before the pull request gets merged?

**Comment by iamkevla** [comment]
Thanks for the PR ur a legend
